### ISSUE TITLE
Adding computed fields for existing content

### ISSUE THREAD

**Issue by mariadermer** [voorhoede/datocms-plugin-computed-fields#14]
When adding a new computed field to an already existing content, we need to go over each record in DatoCMS enter it and save it, so that the field will be computed. Is there an easier way to compute the value of the field for all existing content?

**Comment by velomovies** [comment]
Hi @mariadermer,
Thanks for using our plugin!
We have investigated this and unfortunately it seems there is no easier way. Since you change data of a record that data needs to be fetched and manually be saved. DatoCMS doesn't seem to have, at the moment, an easy way of getting all the data and updating it with the new data/computed field.
