### ISSUE TITLE
Does not work as part of Blocks

### ISSUE THREAD

**Issue by rothnic** [voorhoede/datocms-plugin-computed-fields#23]
We use a number of fields to generate templated text in our current CMS. I was looking at leveraging different blocks as a way to allow adding 1 of a few options for producing the templated text. However, I found that this computed fields plugin does not work with blocks.

I tried adding all the fields feeding into the calculated field, plus the calculated field, then added that to another model and there is a console error about not being available.

Next, I tried to reference the fields in the block from a calculated field directly on the model, but that didn't have access to the block's fields either.

Example:

Block
<img width="704" alt="image" src="https://user-images.githubusercontent.com/452052/208782623-d033ebd9-949d-4ec3-9db8-21537f6c3790.png">

Calculated field:
```
return `${custom_shipping_text} | ${shipping_price}`
```

Error:
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/452052/208782911-0890b0c5-d37b-49ff-81b6-84e2f480060f.png">

**Comment by velomovies** [comment]
Hi @rothnic, thanks for using the plugin and raising this issue. Luckily there is a way around your problem.

It's a difficult problem because the fields are inside a modular content block. This is not initialized by the plugin because you could potentially have more than one block and thus have for example more than one `custom_shipping_text`. 

However if you `console.log(shipping)` (`shipping` is the name of the modular content block in your example) it should return an array `[{ ...shipping items }]`. So in your case you could do:

```js
const [shippingItem] = shipping  // or do const shippingItem = shipping[0] which returns the same value
return `${shippingItem.custom_shipping_text} | ${shippingItem.shipping_price}`
```

This solution is only working correctly if you have only one block in the modular content block. (Which is true in your case)

But when you have more items in a modular content block it becomes a bit more difficult, because you have more than one item in the `shipping` array. You could use the `datoCmsPlugin.fieldPath` variable for that which in your case will be `shipping.0.shipping_text`. Then you have to do some string manipulation and after that return the correct values. You can use the helper function `getFieldValue` for this.

See here my example:

```js
const fieldPath = datoCmsPlugin.fieldPath // Field path of current field ("shipping.0.shipping_text")
const indexOfDot = fieldPath.lastIndexOf('.') // Gets index of last dot (.)
const fieldPathBefore = fieldPath.slice(0, indexOfDot) // Gets fieldPath without the current field (so "shipping.0")

// Get value of item of the field you want to return 
const customShippingText = getFieldValue(datoCmsPlugin.formValues, `${fieldPathBefore}.custom_shipping_text`)
const shippingPrice = getFieldValue(datoCmsPlugin.formValues, `${fieldPathBefore}.shipping_price`)

return `${customShippingText} | ${shippingPrice}`
```

This is maybe not the most elegant, but unfortunately there is (at the moment) no easier way. 

I hope this solves you issue. If you have any more questions feel free to open a new issue

**Comment by rothnic** [comment]
@velomovies thanks a bunch for the reply. I was hoping there would be a workaround, but didn't quite connect these dots. This might be worth linking to from the readme.

**Comment by rothnic** [comment]
@velomovies now that I played around with it a bit, there was one thing I'm not quite following. It seems like the solution you described above the template portion (const fieldPath = ..... const shippingPrice) is generalizable isn't it? In other words, could the plugin not automatically take this approach to make each field in a block available to the calculated field(s) in the block?

**Comment by velomovies** [comment]
@rothnic Good point! Now I think about it, that should indeed be doable.

So we will do this when the field is in a block. We make a new variable i.e. `thisBlock` and then you can do `thisBlock.[dataYouNeed]`. (`thisBlock.custom_shipping_text`)
