### ISSUE TITLE
How to access values within multi-link field?

### ISSUE THREAD

**Issue by slanelb** [voorhoede/datocms-plugin-computed-fields#32]
Hello, I wondered if you could help me?
I would like to access the values within a multi-link field. How should I go about this within your plug-in?
E.g. retrieving the title(string) value of each link of the multi-link field - so I can create an array of titles as a single string. 
Thank you for any advice.

**Comment by velomovies** [comment]
Hi @slanelb, thanks for using this plugin!

This is something that is possible by using the helper function `getModel`

A multi link field always saves the id of the model. This model we can `await` and use the correct field in that model. Since it's an async field you can use promises to get the right data.

An example would be:
```javascript
const multipleLinkField = multiple_link_field // The multiple field key

const promises = multipleLinkField.map(async link => {
  const thisLink = await getModel(link)
  return thisLink.title
})

const allLinks = await Promise.all(promises)

return allLinks
```

I hope this helps you in the right direction. Let me know if this works or feel free to leave questions!

**Comment by slanelb** [comment]
Thank you for your quick and full reply. I will try this. Great plugin!

**Comment by slanelb** [comment]
Works perfectly. Thank you!
