### ISSUE TITLE
Script not firing on field value change.

### ISSUE THREAD

**Issue by hatched-grzegorz** [voorhoede/datocms-plugin-computed-fields#33]
Hi.

Thank you for the awesome plugin!!!

I've noticed that when editing a text field in a block that is placed on a list the script is not firing.
Only after collapsing the block and expanding back again the field gets updated.

Is there something wrong I am doing?

Please see attached video

https://github.com/voorhoede/datocms-plugin-computed-fields/assets/60889650/264406a8-6a08-4344-adc2-0d45c13ca3e9

**Comment by velomovies** [comment]
Hi @hatched-grzegorz, thanks for using the plugin and thanks for raising this issue. This is indeed a bug from our side. The problem was that we only triggered updating a field when the fieldPath was in the code. Since `thisBlock` isn't the actual fieldPath of the changed field it didn't update. 

We now extended the check and should be available in version `2.4.5` when DatoCMS picked it up

**Comment by hatched-grzegorz** [comment]
Thanks for such a swift response!
I will definitely update as soon as possible.

**Comment by hatched-grzegorz** [comment]
@velomovies 
I am afraid that this update removed triggering of the script for the field when a field of one of the children blocks is edited.
```
{
  computed-field
  block-list {
    some-block {
      edited-text-field
    }
  }
}
```
The computed-field is not being recalculated when edited-text-field is changed.
Only saving the whole record and reopening it recalculates the field.
This worked on previous version.
