### ISSUE TITLE
Get ID of current record

### ISSUE THREAD

**Issue by johannesmutter** [voorhoede/datocms-plugin-computed-fields#9]
Hi there,

Is it possible to access the ID of the current record?

For example I have an optional title field named "title".
I want to compute a slug from the title, but if no title is provided I want to use the ID of the record.

```
return `${title ? title : 'untitled'} ${id}`
```

But ID (id) is undefined.

**Comment by velomovies** [comment]
Hi @johannesmutter!

At the moment there is no direct way to get the `id` of a record.

There is, however, a work around. Since you can run any code in this plugin you could for now handle this by using `this` (which would be the `window`) and initiate a plugin inside the plugin. You will get all plugin options and methods and thus it will give you access to `plugin.itemId`.

```javascript
let recordId
await this.DatoCmsPlugin.init((plugin) => {
  recordId = plugin.itemId
})

return `${title ? title : 'untitled'} ${recordId}`
```

All options and methods you get returned are listed here: https://www.datocms.com/docs/building-plugins/sdk-reference
I hope this helps you!

**Comment by johannesmutter** [comment]
Awesome! Thank you

**Comment by velomovies** [comment]
When updating to version 2.0 of the computed fields plugin this won't work anymore. In version 2.0 there will be a `datoCmsPlugin` variable.

`datoCmsPlugin` will return the whole plugin context. In the [documentation](https://www.datocms.com/docs/plugin-sdk) you can see what properties and methods are exposed. The `datoCmsPlugin` variable is `ctx` of a field extension with the declared type: [RenderFieldExtensionCtx](https://github.com/datocms/plugins-sdk/blob/19af57b61bd763cdb9c3d4aa945408b577602cc0/packages/sdk/src/connect.ts#L72).

You can do
```js
return datoCmsPlugin.itemId
```

or in the example of this issue
```js
const recordId = datoCmsPlugin.itemId
return `${title ? title : 'untitled'} ${recordId}`
```
